### ISSUE TITLE
Some Games are not working?

### ISSUE THREAD

**Issue by fubaWoW** [dlprows/FocusVolumeControl#11] opened 2024-04-08 19:44 UTC
Hi there,

Some Games are not recognized correctly!
In my Case it is Path of Exile and now Helldivers 2.
maybe you can take a look into it?

**Comment by dlprows** [comment] 2024-04-21 04:03
Sorry it took so long to respond.

I haven't been able to reproduce an issue with Path of Exile. Though if I recall correctly, I think there's a steam and non-steam version. I think in the past I had used the non-steam version, and I was testing on the steam version. Given what's wrong with Helldivers, its certainly possible that the steam and non-steam versions could behave differently.

Helldivers 2 uses a particularly aggressive form of anti-cheat that messes with the plugin's ability to get information about the focused window, and match to the correct audio process.

I had previously done some work on it https://github.com/dlprows/FocusVolumeControl/issues/10
But after I finished that, I was unsatisfied with the solution, because it only fixed Helldivers 2, and it did so with code very specifically for it.


So I've done some work to make an overrides mechanism so that if particular applications are giving you trouble, you can just tell it how to do the mapping. Certainly not as ideal as it magically working, but unfortunately there's only so much I can do.


There's a pre-release I'll be using for a week or so to make sure it works before I send it to elgato.
You're welcome to download it early and test it

https://github.com/dlprows/FocusVolumeControl/releases/tag/v1.3.0

**Comment by fubaWoW** [comment] 2024-04-21 10:13
> Sorry it took so long to respond.

No problem!

> I haven't been able to reproduce an issue with Path of Exile

i used the Steam Version where it was not working correctly
BUT it worked with you Plugin version 1.1.2 and not with 1.2.0... anyhow?!

> Helldivers 2 uses a particularly aggressive form of anti-cheat

yeah i know -> this is very disappointing!

> You're welcome to download it early and test it

Thanks!
I will download, try and report if it is working or not.

greetings

**Comment by dlprows** [comment] 2024-05-07 21:00
Apparently, the new version has been published, and I didn't notice the email from them.
Closing

**Closed as completed by dlprows** 2024-05-07 21:00 UTC
